#!/usr/bin/env bash

ls src/raw/applicatives/applicative.md
ls src/raw/applicatives/builder.md
ls src/raw/applicatives/cartesian.md
ls src/raw/applicatives/index.md
ls src/raw/applicatives/summary.md
ls src/raw/applicatives/validated.md
ls src/raw/case-studies/mapreduce/index.md
ls src/raw/case-studies/parser/index.md
ls src/raw/case-studies/validation/check.md
ls src/raw/case-studies/validation/conclusions.md
ls src/raw/case-studies/validation/index.md
ls src/raw/case-studies/validation/kleisli.md
ls src/raw/case-studies/validation/map.md
ls src/raw/case-studies/validation/sketch.md
ls src/raw/foldable/cats.md
ls src/raw/foldable/index.md
ls src/raw/foldable/summary.md
ls src/raw/functors/cats.md
ls src/raw/functors/index.md
ls src/raw/functors/summary.md
ls src/raw/intro/acknowledgements.md
ls src/raw/intro/conventions.md
ls src/raw/intro/early-access.md
ls src/raw/intro/foreword.md
ls src/raw/links.md
ls src/raw/monad-transformers/index.md
ls src/raw/monad-transformers/summary.md
ls src/raw/monads/cats.md
ls src/raw/monads/error-recovery.md
ls src/raw/monads/eval.md
ls src/raw/monads/id.md
ls src/raw/monads/index.md
ls src/raw/monads/reader.md
ls src/raw/monads/state.md
ls src/raw/monads/writer.md
ls src/raw/monads/xor.md
ls src/raw/monoids/cats.md
ls src/raw/monoids/index.md
ls src/raw/monoids/instance-selection.md
ls src/raw/solutions.md
ls src/raw/type-classes/anatomy.md
ls src/raw/type-classes/cats.md
ls src/raw/type-classes/equal.md
ls src/raw/type-classes/index.md
ls src/raw/type-classes/summary.md
