#import "stdlib.typ": info, warning, solution
[scala.Option]: http://www.scala-lang.org/api/current/scala/Option.html
[scala.=:=]: https://www.scala-lang.org/api/current/scala/=:=.html
[scala.<:<]: https://www.scala-lang.org/api/current/scala/<:<.html
[scala.NotGiven]: https://www.scala-lang.org/api/current/scala/util/NotGiven.html

[cats.package]: http://typelevel.org/cats/api/cats/
[cats.Apply]: http://typelevel.org/cats/api/cats/Apply.html
[cats.Applicative]: http://typelevel.org/cats/api/cats/Applicative.html
[cats.ApplicativeError]: http://typelevel.org/cats/api/cats/ApplicativeError.html
[cats.Eval]: http://typelevel.org/cats/api/cats/Eval.html
[cats.Contravariant]: http://typelevel.org/cats/api/cats/Contravariant.html
[cats.Invariant]: http://typelevel.org/cats/api/cats/Invariant.html
[cats.Functor]: http://typelevel.org/cats/api/cats/Functor.html
[cats.Id]: http://typelevel.org/cats/api/cats/Id.html
[cats.Monoid]: http://typelevel.org/cats/api/cats/kernel/Monoid.html
[cats.Monad]: http://typelevel.org/cats/api/cats/Monad.html
[cats.MonadError]: http://typelevel.org/cats/api/cats/MonadError.html
[cats.Show]: http://typelevel.org/cats/api/cats/Show.html
[cats.Semigroup]: http://typelevel.org/cats/api/cats/kernel/Semigroup.html
[cats.Semigroupal]: http://typelevel.org/cats/api/cats/Semigroupal.html
[cats.Traverse]: http://typelevel.org/cats/api/cats/Traverse.html
[cats.arrow.FunctionK]: http://typelevel.org/cats/api/cats/arrow/FunctionK.html
[cats.data]: http://typelevel.org/cats/api/cats/data/
[cats.data.IdT]: http://typelevel.org/cats/api/cats/data/IdT.html
[cats.data.Kleisli]: http://typelevel.org/cats/api/cats/data/Kleisli.html
[cats.data.NonEmptyList]: http://typelevel.org/cats/api/cats/data/NonEmptyList.html
[cats.data.NonEmptyVector]: http://typelevel.org/cats/api/cats/data/NonEmptyVector.html
[cats.data.OptionT]: http://typelevel.org/cats/api/cats/data/OptionT.html
[cats.data.package]: http://typelevel.org/cats/api/cats/data/
[cats.data.Reader]: http://typelevel.org/cats/api/cats/data/?search=reader#Reader[A,B]=cats.data.package.ReaderT[cats.Id,A,B]
[cats.data.ReaderT]: http://typelevel.org/cats/api/cats/data/?search=reader#ReaderT[F[_],A,B]=cats.data.Kleisli[F,A,B]
[cats.data.State]: http://typelevel.org/cats/api/cats/data/#State[S,A]=cats.data.StateT[cats.Eval,S,A]
[cats.data.StateT]: http://typelevel.org/cats/api/cats/data/StateT.html
[cats.data.Validated]: http://typelevel.org/cats/api/cats/data/Validated.html
[cats.data.Writer]: http://typelevel.org/cats/api/cats/data/#Writer[S,A]=cats.data.WriterT[cats.Eval,S,A]
[cats.data.WriterT]: http://typelevel.org/cats/api/cats/data/WriterT.html
[cats.data.EitherT]: http://typelevel.org/cats/api/cats/data/EitherT.html
[cats.implicits]: http://typelevel.org/cats/api/cats/implicits$.html
[cats.instances]: http://typelevel.org/cats/api/cats/instances/
[cats.instances.all]: http://typelevel.org/cats/api/cats/instances/package$$all$
[cats.instances.int]: http://typelevel.org/cats/api/cats/instances/package$$int$
[cats.instances.string]: http://typelevel.org/cats/api/cats/instances/package$$string$
[cats.instances.list]: http://typelevel.org/cats/api/cats/instances/package$$list$
[cats.instances.option]: http://typelevel.org/cats/api/cats/instances/package$$option$
[cats.instances.map]: http://typelevel.org/cats/api/cats/instances/package$$map$
[cats.instances.try_]: http://typelevel.org/cats/api/cats/instances/package$$try_$
[cats.kernel.package]: http://typelevel.org/cats/api/cats/kernel/
[cats.kernel.CommutativeMonoid]: https://typelevel.org/cats/api/cats/kernel/CommutativeMonoid.html
[cats.kernel.Eq]: http://typelevel.org/cats/api/cats/kernel/Eq.html
[cats.kernel.Monoid]: http://typelevel.org/cats/api/cats/kernel/Monoid.html
[cats.kernel.Semigroup]: http://typelevel.org/cats/api/cats/kernel/Semigroup.html
[cats.syntax]: http://typelevel.org/cats/api/cats/syntax/
[cats.syntax.applicative]: http://typelevel.org/cats/api/cats/syntax/package$$applicative$
[cats.syntax.applicativeError]: http://typelevel.org/cats/api/cats/syntax/package$$applicativeError$
[cats.syntax.apply]: http://typelevel.org/cats/api/cats/syntax/package$$semigroupal$
[cats.syntax.contravariant]: http://typelevel.org/cats/api/cats/syntax/package$$contravariant$
[cats.syntax.either]: http://typelevel.org/cats/api/cats/syntax/package$$either$
[cats.syntax.eq]: http://typelevel.org/cats/api/cats/syntax/package$$eq$
[cats.syntax.flatMap]: http://typelevel.org/cats/api/cats/syntax/package$$flatMap$
[cats.syntax.foldable]: http://typelevel.org/cats/api/cats/syntax/package$$foldable$
[cats.syntax.functor]: http://typelevel.org/cats/api/cats/syntax/package$$functor$
[cats.syntax.monadError]: http://typelevel.org/cats/api/cats/syntax/package$$monadError$
[cats.syntax.option]: http://typelevel.org/cats/api/cats/syntax/package$$option$
[cats.syntax.semigroup]: http://typelevel.org/cats/api/cats/syntax/package$$semigroup$
[cats.syntax.show]: http://typelevel.org/cats/api/cats/syntax/package$$show$
[cats.syntax.traverse]: http://typelevel.org/cats/api/cats/syntax/package$$traverse$
[cats.syntax.writer]: http://typelevel.org/cats/api/cats/syntax/package$$writer$

[scalaz.\/]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.$bslash$div
[scalaz.Applicative]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Applicative
[scalaz.Cord]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Cord
[scalaz.Equal]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Equal
[scalaz.Foldable]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Foldable
[scalaz.Functor]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Functor
[scalaz.Monad]: http://docs.typelevel.org/api/scalaz/nightly/index.html#scalaz.Monad
[scalaz.MonadTrans]: http://docs.typelevel.org/api/scalaz/nightly/index.html#scalaz.MonadTrans
[scalaz.Monoid]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Monoid
[scalaz.NaturalTransformation]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.NaturalTransformation
[scalaz.Show]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Show
[scalaz.Tag]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Tag$
[scalaz.Traversable]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.Traversable
[scalaz.OptionT]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.OptionT
[scalaz.ListT]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.ListT
[scalaz.EitherT]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.EitherT
[scalaz.ReaderT]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.ReaderT
[scalaz.WriterT]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.WriterT
[scalaz.IdT]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.IdT
[scalaz.instances.anyVal]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.instances.anyVal$
[scalaz.instances.list]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.instances.list$
[scalaz.instances.map]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.instances.map$
[scalaz.instances.option]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.instances.option$
[scalaz.instances.string]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.instances.string$
[scalaz.instances.tuple]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.instances.tuple$
[scalaz.instances]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.instances.package
[scalaz.syntax.equal]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.syntax.Syntaxes$equal$
[scalaz.syntax.show]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.syntax.Syntaxes$show$
[scalaz.syntax.traverse]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.syntax.Syntaxes$traverse$
[scalaz.syntax]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.syntax.package
[scalaz]: http://docs.typelevel.org/api/scalaz/stable/7.0.4/doc/#scalaz.package

[link-algebird]: https://github.com/twitter/algebird
[link-applicative-programming]: http://www.staff.city.ac.uk/~ross/papers/Applicative.html
[link-bloom-filter]: http://en.wikipedia.org/wiki/Bloom_filter
[link-bnf]: https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_Form
[link-cats]: http://typelevel.org/cats
[link-cats-infographic]: https://github.com/tpolecat/cats-infographic
[link-circe-codec]: https://github.com/circe/circe/blob/series/0.14.x/modules/core/shared/src/main/scala/io/circe/Codec.scala
[link-crdt-survey]: https://hal.inria.fr/inria-00609399v2/document
[link-don-stewart-so]: http://stackoverflow.com/questions/27852709/enterprise-patterns-with-functional-programming/27860072#27860072
[link-don-stewart]: https://donsbot.wordpress.com
[link-essential-scala]: http://underscore.io/books/essential-scala
[link-github]: https://github.com/scalawithcats/scala-with-cats
[link-hadoop]: http://hadoop.apache.org
[link-hyperloglog]: http://en.wikipedia.org/wiki/HyperLogLog
[link-implicit-priority]: http://eed3si9n.com/revisiting-implicits-without-import-tax
[link-iterator-pattern]: https://www.cs.ox.ac.uk/jeremy.gibbons/publications/iterator.pdf
[link-json]: http://json.org/
[link-kind-projector]: https://github.com/typelevel/kind-projector
[link-map-reduce-monoid]: http://arxiv.org/abs/1304.7544
[link-map-reduce]: http://research.google.com/archive/map-reduce.html
[link-mdoc]: https://github.com/scalameta/mdoc
[link-monads-burritos]: http://blog.plover.com/prog/burritos.html
[link-monocle]: https://github.com/optics-dev/Monocle
[link-parallel-collections]: http://docs.scala-lang.org/overviews/parallel-collections/overview.html
[link-phil-freeman-tailrecm]: http://functorial.com/stack-safety-for-free/index.pdf
[link-play-json-format]: https://www.playframework.com/documentation/2.6.x/ScalaJsonCombinators#Format
[link-sbt]: http://www.scala-sbt.org/
[link-scalactic]: http://scalactic.org
[link-scalaz-contrib]: https://github.com/typelevel/scalaz-contrib
[link-scodec-codec]: http://scodec.org/guide/Core+Algebra.html#Codec
[link-si2712-compiler-plugin]: https://github.com/milessabin/si2712fix-plugin
[link-si2712]: https://issues.scala-lang.org/browse/SI-2712
[link-si-6680]: https://issues.scala-lang.org/browse/SI-6680
[link-simulacrum]: https://github.com/mpilquist/simulacrum
[link-so-future]: https://www.reddit.com/r/scala/comments/3zofjl/why_is_future_totally_unusable/
[link-so-implicit-scope]: https://stackoverflow.com/questions/5598085/where-does-scala-look-for-implicits
[link-so-tree-tailrecm]: https://stackoverflow.com/questions/44504790/cats-non-tail-recursive-tailrecm-method-for-monads
[link-stochastic-gradient-descent]: http://en.wikipedia.org/wiki/Stochastic_gradient_descent
[link-summingbird]: https://github.com/twitter/summingbird
[link-symbol]: https://www.scala-lang.org/api/3.3.3/scala/Symbol.html#
[link-topk]: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.114.9563
[link-typelevel-scala]: https://github.com/typelevel/scala
[link-value-classes]: http://docs.scala-lang.org/overviews/core/value-classes.html
[link-gibbons-oliviera-iterator-pattern]: https://www.cs.ox.ac.uk/jeremy.gibbons/publications/iterator.pdf
[link-underscore]: https://underscore.io
