#import "../stdlib.typ": info, warning, solution
= Acknowledgements


No book is an island.
This book wouldn't exist without it's predecessor, _Scala with Cats_, and everyone involved in creating that book implicitly played some part in this book's creation.
See below for that book's acknowledgements, but in particular I want to highlight my coauthor,
Dave "Lord of Types" Pereira-Gurnell, without whom that book would not exist and hence neither would this one.
Thanks Dave!

Thanks also to Adam Rosien, who gave me low-key encouragement and put up with my bullshit. Also my wife and children, who put up with even more of my bullshit, and gave me the space to finish this project.
The members of ScalaBridge London and attendees at various training courses acted as experimental subjects for a lot of the material here. Thank you for being willing test subjects; you greatly helped improve the content.
Thanks for the members of the PLT research group who inspired me directly back in the day, and continue to provide inspiration from afar.
Finally, thanks to the following who sponsored my work or contributed with corrections and suggestions:

Aleksandr Andreev,
Charles Adetiloye,
Johanna Odersky,
Lunfu Zhong,
Maciej Gorywoda ,
Mathieu Pichette,
Murat Cetin ,
Olya Mazhara,
Pavel Syvak,
Philip Schwarz,
Seth Tisue,
Tim Eccleston (#link("https://github.com/combinatorist")[\@combinatorist]).


== Acknowledgements from Scala with Cats


We'd like to thank our colleagues at Inner Product and Underscore,
our friends at Typelevel,
and everyone who helped contribute to this book.
Special thanks to Jenny Clements for her fantastic artwork
and Richard Dallaway for his proof reading expertise.
Here is an alphabetical list of contributors:

Alessandro Marrella,
Cody Koeninger,
Connie Chen,
Conor Fennell,
Dani Rey,
Daniela Sfregola,
Danielle Ashley,
David Castillo,
David Piggott,
Denis Zjukow,
Dennis Hunziker,
Deokhwan Kim,
Edd Steel,
Eduardo Obando Boschini,
Eugene Yushin,
Evgeny Veretennikov,
Francis Devereux,
Ghislain Vaillant,
Gregor Ihmor,
Hayato Iida,
Henk-Jan Meijer,
HigherKindedType,
Janne Pelkonen,
Joao Azevedo,
Jason Scott,
Javier Arrieta,
Jenny Clements,
Jérémie Jost,
Joachim Hofer,
Jonathon Ferguson,
Lance Paine,
Leif Wickland,
ltbs,
Lunfu Zhong,
Marc Prud'hommeaux,
Martin Carolan,
mizuno,
Mr-SD,
Narayan Iyer,
Niccolo' Paravanti,
niqdev,
Noor Nashid,
Pablo Francisco Pérez Hidalgo,
Pawel Jurczenko,
Phil Derome,
Philip Schwarz,
Riccardo Sirigu,
Richard Dallaway,
Robert Stoll,
Rodney Jacobsen,
Rodrigo B. de Oliveira,
Rud Wangrungarun,
Seoh Char,
Sergio Magnacco,
Shohei Shimomura,
Tim McIver,
Toby Weston,
Victor Osolovskiy,
and Yinka Erinle.

If you spot an error or potential improvement,
please raise an issue or submit a PR
on the book's [Github page][link-github].


=== Backers {-}


We'd also like to extend very special thanks
to our backers---fine people who helped
fund the development of the book by buying a copy
before we released it as open source.
This book wouldn't exist without you:

A battle-hardened technologist,
Aaron Pritzlaff,
Abhishek Srivastava,
Aleksey "Daron" Terekhin,
Algolia,
Allen George (&commat;allenageorge),
Andrew Johnson,
Andrew Kerr,
Andy Dwelly,
Anler,
anthony\@dribble.ai,
Aravindh Sridaran,
Araxis Ltd,
ArtemK,
Arthur Kushka (&commat;arhelmus),
Artur Zhurat,
Arturas Smorgun,
Attila Mravik,
Axel Gschaider,
Bamboo Le,
bamine,
Barry Kern,
Ben Darfler (&commat;bdarfler),
Ben Letton,
Benjamin Neil,
Benoit Hericher,
Bernt Andreas Langøien,
Bill Leck,
Blaze K,
Boniface Kabaso,
Brian Wongchaowart,
Bryan Dragon,
&commat;cannedprimates,
Ceschiatti (&commat;6qat),
Chris Gojlo,
Chris Phelps,
&commat;CliffRedmond,
Cody Koeninger,
Constantin Gonciulea,
Dadepo Aderemi,
Damir Vandic,
Damon Rolfs,
Dan Todor,
Daniel Arndt,
Daniela Sfregola,
David Greco,
David Poltorak,
Dennis Hunziker,
Dennis Vriend,
Derek Morr,
Dimitrios Liapis,
Don McNamara,
Doug Clinton,
Doug Lindholm (dlindhol),
Edgar Mueller,
Edward J Renauer Jr,
Emiliano Martinez,
esthom,
Etienne Peiniau,
Fede Silva,
Filipe Azevedo,
Franck Rasolo,
Gary Coady,
George Ball,
Gerald Loeffler, Integrational,
Giles Taylor,
Guilherme Dantas (&commat;gamsd),
Harish Hurchurn,
Hisham Ismail,
Iurii Susuk,
Ivan (SkyWriter) Kasatenko,
Ivano Pagano,
Jacob Baumbach,
James Morris,
Jan Vincent Liwanag,
Javier Gonzalez,
Jeff Gentry,
Joel Chovanec,
Jon Bates,
Jorge Aliss (&commat;jaliss),
Juan Macias (&commat;1macias1),
Juan Ortega,
Juan Pablo Romero Méndez,
Jungsun Kim,
Kaushik Chakraborty (&commat;kaychaks),
Keith Mannock,
Ken Hoffman,
Kevin Esler,
Kevin Kyyro,
kgillies,
Klaus Rehm,
Kostas Skourtis,
Lance Linder,
Liang, Guang Hua,
Loïc Girault,
Luke Tebbs,
Makis A,
Malcolm Robbins,
Mansur Ashraf (&commat;mansur_ashraf),
Marcel Lüthi,
Marek Prochera &commat;hicolour,
Marianudo (Mariano Navas),
Mark Eibes,
Mark van Rensburg,
Martijn Blankestijn,
Martin Studer,
Matthew Edwards,
Matthew Pflueger,
mauropalsgraaf,
mbarak,
Mehitabel,
Michael Pigg,
Mikael Moghadam,
Mike Gehard (&commat;mikegehard),
MonadicBind,
arjun.mukherjee&commat;gmail.com,
Stephen Arbogast,
Narayan Iyer,
&commat;natewave,
Netanel Rabinowitz,
Nick Peterson,
Nicolas Sitbon,
Oier Blasco Linares,
Oliver Daff,
Oliver Schrenk,
Olly Shaw,
P Villela,
pandaforme,
Patrick Garrity,
Pawel Wlodarski from JUG Lodz,
&commat;peel,
Peter Perhac,
Phil Glover,
Philipp Leser-Wolf,
Rachel Bowyer,
Radu Gancea (&commat;radusw),
Rajit Singh,
Ramin Alidousti,
Raymond Tay,
Riccardo Sirigu,
Richard (Yin-Wu) Chuo,
Rob Vermazeren,
Robert "Kemichal" Andersson,
Robin Taylor (&commat;badgermind),
Rongcui Dong,
Rui Morais,
Rupert Bates,
Rustem Suniev,
Sanjiv Sahayam,
Shane Delmore,
Stefan Plantikow,
Sundy Wiliam Yaputra,
Tal Pressman,
Tamas Neltz,
theLXK,
Tim Pigden,
Tobias Lutz,
Tom Duhourq,
&commat;tomzalt,
Utz Westermann,
Vadym Shalts,
Val Akkapeddi,
Vasanth Loka,
Vladimir Bacvanski,
Vladimir Bystrov aka udav_pit,
William Benton,
Wojciech Langiewicz,
Yann Ollivier (&commat;ya2o),
Yoshiro Naito,
zero323,
and zeronone.
